[build]
  Functions = "functions"
  command = "yarn run build"
  publish = "dist"
  environment = { NODE_VERSION = "8.9.0" }


[[headers]]
  for = "/index.html"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

    #  Multi-value headers are expressed with multi-line strings
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''

    # The Basic-Auth header may not be available on all plans.
    Basic-Auth = "chay:javy"



[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

